# Generated by Django 4.1.4 on 2022-12-24 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Meals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("meal", models.CharField(max_length=100)),
                ("calID", models.CharField(max_length=100)),
            ],
        ),
    ]
