# Generated by Django 4.1.4 on 2022-12-24 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MealPlanning", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Meals",
            new_name="Meal",
        ),
    ]
