# Generated by Django 4.1.4 on 2022-12-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MealPlanning", "0002_rename_meals_meal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meal",
            name="id",
        ),
        migrations.AlterField(
            model_name="meal",
            name="calID",
            field=models.CharField(max_length=1000, primary_key=True, serialize=False),
        ),
    ]
