# Generated by Django 4.1.4 on 2022-12-24 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MealPlanning", "0003_remove_meal_id_alter_meal_calid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="meal",
            old_name="calID",
            new_name="eventID",
        ),
    ]
